# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-29 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='staffprofileinfo',
            name='protfolio_site',
            field=models.URLField(blank=True),
        ),
    ]
